
CREATE TABLE Authors (
    AuthorID INT PRIMARY KEY,
    AuthorName NVARCHAR(255)
);

INSERT INTO Authors (AuthorID, AuthorName) VALUES (1, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (2, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (3, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (4, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (5, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (6, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (7, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (8, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (9, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (10, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (11, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (12, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (13, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (14, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (15, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (16, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (17, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (18, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (19, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (20, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (21, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (22, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (23, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (24, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (25, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (26, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (27, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (28, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (29, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (30, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (31, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (32, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (33, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (34, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (35, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (36, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (37, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (38, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (39, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (40, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (41, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (42, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (43, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (44, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (45, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (46, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (47, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (48, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (49, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (50, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (51, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (52, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (53, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (54, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (55, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (56, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (57, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (58, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (59, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (60, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (61, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (62, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (63, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (64, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (65, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (66, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (67, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (68, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (69, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (70, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (71, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (72, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (73, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (74, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (75, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (76, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (77, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (78, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (79, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (80, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (81, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (82, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (83, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (84, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (85, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (86, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (87, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (88, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (89, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (90, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (91, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (92, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (93, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (94, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (95, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (96, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (97, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (98, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (99, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (100, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (101, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (102, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (103, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (104, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (105, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (106, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (107, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (108, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (109, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (110, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (111, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (112, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (113, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (114, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (115, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (116, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (117, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (118, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (119, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (120, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (121, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (122, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (123, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (124, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (125, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (126, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (127, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (128, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (129, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (130, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (131, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (132, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (133, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (134, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (135, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (136, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (137, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (138, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (139, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (140, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (141, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (142, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (143, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (144, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (145, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (146, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (147, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (148, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (149, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (150, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (151, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (152, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (153, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (154, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (155, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (156, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (157, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (158, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (159, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (160, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (161, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (162, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (163, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (164, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (165, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (166, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (167, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (168, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (169, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (170, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (171, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (172, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (173, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (174, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (175, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (176, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (177, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (178, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (179, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (180, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (181, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (182, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (183, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (184, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (185, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (186, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (187, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (188, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (189, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (190, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (191, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (192, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (193, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (194, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (195, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (196, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (197, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (198, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (199, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (200, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (201, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (202, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (203, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (204, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (205, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (206, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (207, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (208, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (209, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (210, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (211, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (212, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (213, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (214, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (215, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (216, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (217, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (218, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (219, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (220, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (221, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (222, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (223, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (224, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (225, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (226, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (227, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (228, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (229, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (230, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (231, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (232, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (233, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (234, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (235, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (236, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (237, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (238, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (239, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (240, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (241, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (242, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (243, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (244, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (245, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (246, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (247, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (248, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (249, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (250, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (251, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (252, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (253, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (254, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (255, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (256, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (257, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (258, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (259, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (260, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (261, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (262, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (263, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (264, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (265, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (266, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (267, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (268, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (269, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (270, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (271, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (272, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (273, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (274, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (275, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (276, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (277, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (278, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (279, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (280, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (281, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (282, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (283, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (284, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (285, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (286, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (287, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (288, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (289, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (290, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (291, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (292, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (293, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (294, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (295, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (296, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (297, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (298, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (299, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (300, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (301, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (302, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (303, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (304, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (305, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (306, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (307, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (308, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (309, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (310, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (311, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (312, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (313, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (314, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (315, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (316, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (317, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (318, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (319, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (320, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (321, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (322, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (323, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (324, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (325, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (326, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (327, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (328, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (329, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (330, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (331, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (332, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (333, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (334, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (335, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (336, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (337, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (338, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (339, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (340, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (341, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (342, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (343, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (344, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (345, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (346, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (347, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (348, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (349, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (350, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (351, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (352, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (353, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (354, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (355, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (356, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (357, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (358, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (359, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (360, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (361, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (362, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (363, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (364, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (365, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (366, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (367, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (368, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (369, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (370, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (371, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (372, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (373, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (374, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (375, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (376, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (377, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (378, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (379, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (380, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (381, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (382, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (383, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (384, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (385, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (386, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (387, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (388, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (389, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (390, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (391, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (392, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (393, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (394, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (395, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (396, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (397, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (398, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (399, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (400, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (401, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (402, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (403, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (404, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (405, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (406, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (407, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (408, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (409, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (410, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (411, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (412, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (413, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (414, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (415, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (416, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (417, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (418, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (419, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (420, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (421, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (422, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (423, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (424, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (425, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (426, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (427, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (428, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (429, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (430, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (431, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (432, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (433, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (434, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (435, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (436, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (437, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (438, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (439, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (440, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (441, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (442, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (443, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (444, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (445, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (446, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (447, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (448, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (449, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (450, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (451, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (452, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (453, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (454, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (455, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (456, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (457, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (458, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (459, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (460, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (461, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (462, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (463, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (464, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (465, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (466, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (467, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (468, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (469, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (470, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (471, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (472, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (473, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (474, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (475, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (476, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (477, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (478, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (479, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (480, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (481, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (482, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (483, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (484, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (485, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (486, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (487, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (488, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (489, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (490, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (491, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (492, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (493, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (494, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (495, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (496, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (497, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (498, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (499, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (500, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (501, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (502, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (503, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (504, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (505, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (506, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (507, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (508, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (509, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (510, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (511, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (512, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (513, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (514, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (515, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (516, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (517, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (518, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (519, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (520, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (521, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (522, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (523, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (524, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (525, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (526, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (527, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (528, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (529, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (530, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (531, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (532, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (533, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (534, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (535, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (536, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (537, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (538, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (539, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (540, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (541, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (542, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (543, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (544, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (545, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (546, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (547, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (548, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (549, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (550, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (551, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (552, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (553, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (554, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (555, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (556, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (557, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (558, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (559, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (560, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (561, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (562, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (563, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (564, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (565, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (566, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (567, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (568, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (569, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (570, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (571, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (572, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (573, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (574, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (575, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (576, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (577, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (578, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (579, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (580, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (581, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (582, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (583, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (584, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (585, N'Laini Taylor');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (586, N'Victoria Aveyard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (587, N'Charles Duhigg');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (588, N'John Berendt');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (589, N'Colleen Hoover');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (590, N'Frances Hodgson Burnett');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (591, N'Sarah Dessen');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (592, N'C.S. Lewis');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (593, N'Richelle Mead');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (594, N'Laura Ingalls Wilder');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (595, N'Margery Williams Bianco');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (596, N'Robert M. Pirsig');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (597, N'H.G. Wells');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (598, N'Sara Shepard');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (599, N'Don Freeman');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (600, N'Michael Pollan');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (601, N'Seamus Heaney');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (602, N'Frank Miller');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (603, N'Harper Lee');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (604, N'David Sedaris');
INSERT INTO Authors (AuthorID, AuthorName) VALUES (605, N'Laini Taylor');